name: ci

on:
  push:
    branches:
      - '**'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner  }}
          password: ${{ secrets.CR_PAT  }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: tools
          push: true
          tags: ghcr.io/turing-complet/tools:latest
